apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  namespace: blocky
spec:
  project: default
  source:
    chart: blocky
    repoURL: https://github.com/k8s-at-home/charts/tree/master/charts/stable/blocky
    helm:
      releaseName: blocky
      valueFiles:
      - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: blocky
