apiVersion: v2
name: blocky
kind: Application
metadata:
  namespace: blocky
appVersion: "1.0"
spec:
  project: default
  source:
    chart: blocky
    repoURL: https://github.com/k8s-at-home/charts/tree/master/charts/stable/blocky
